include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # @JsonKey annotations inside @freezed factory constructors are valid
    # but the analyzer incorrectly flags them - this is a known false positive
    invalid_annotation_target: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
