-- Add a unique constraint to user_id to enable upserting on it.
-- This ensures each authentication user has exactly one caregiver profile.
ALTER TABLE public.caregiver_profiles 
ADD CONSTRAINT caregiver_profiles_user_id_unique UNIQUE(user_id);

-- Ensure the id column (UUID) has a default value generated by Postgres.
-- This allows the Flutter app to send 'null' for the id during creation.
ALTER TABLE public.caregiver_profiles 
ALTER COLUMN id SET DEFAULT gen_random_uuid();
